-- -----------------------------------------------------
-- Schema Okanban
-- -----------------------------------------------------
BEGIN;

DROP TABLE IF EXISTS "list",
"card",
"label",
"card_has_label";

-- -----------------------------------------------------
-- Table "list"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "list" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "position" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,--on peut utiliser now() aussi
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "card"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "card" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "color" text NULL,
  "position" integer NULL,
  "list_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "label"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "label" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "color" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "card_has_label"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "card_has_label" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "card_id" integer NOT NULL REFERENCES "card"("id"),
  "label_id" integer NOT NULL REFERENCES "label" ("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz, 
  UNIQUE ("card_id", "label_id")
);

ALTER TABLE "card"
  ADD FOREIGN KEY ("list_id") REFERENCES "list" ("id");


-- TESTS SEEDING

INSERT INTO "list" ("id", "title", "position") VALUES
(1, 'To do', 1),
(2, 'Doing', 2),
(3, 'Done', 3),

INSERT INTO "card" ("id", "title", "color", "position", "list_id") VALUES
(1, 'Comptabilité Mars', 'red', 1 , 1),
(2, 'Répondre appel à projet', 1 , 2),

INSERT INTO "label" ("id", "name") VALUES
(1, 'Urgent', 'red'),
(2, 'Délai supp'),

INSERT INTO "card_has_label" ("card_id", "label_id") VALUES
(1, 1),

COMMIT;